version: '3'
services:
  adsb-mongo:
    image: mongo:latest
    container_name: "adsb-mongo"
    networks: 
      - local-adsb-radar
    ports:
      - "27017:27017"

  adsb-radar:
    build:
      context: .
    container_name: "adsb-radar"
    networks: 
      - local-adsb-radar
    ports:
      - "4600:4600"
    environment:
      - MONGODB_HOST=mongodb://adsb-mongo:27017
      - MODE_S_RTL_HOST=10.0.0.11:30002
      - MODE_S_RTL_RETRY_INTERVAL=2500

networks: 
  local-adsb-radar: